# Generated by Django 4.1.6 on 2023-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdata',
            name='Comment',
            field=models.CharField(default='Here User comment ....', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='Edge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='Frame',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='Middle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='Missed',
            field=models.IntegerField(default=0),
        ),
    ]
