# Generated by Django 4.1.6 on 2023-02-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0002_trainingdata_comment_trainingdata_edge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='Frame',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
