# Generated by Django 4.1.6 on 2023-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0003_alter_trainingdata_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='Frame',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
