# Generated by Django 4.1.7 on 2023-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiBackend", "0004_alter_trainingdata_frame"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingdata",
            name="Frame",
            field=models.FileField(upload_to="images/"),
        ),
    ]
